/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.model.bean.Cliente;
import com.model.bean.Mesa;
import com.model.bean.Produto;
import com.model.dao.MesaDAO;
import com.model.dao.ClienteDAO;
import com.model.dao.ProdutoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CadastroCliente() {
        initComponents();
        
         MesaDAO tdao = new MesaDAO();
         for(Mesa m: tdao.FindAll()){
       
            mesaComboBox.addItem(m);
       }
         
         ProdutoDAO pdao = new ProdutoDAO();
         for(Produto p: pdao.FindAll()){
       
            produtoComboBox.addItem(p);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeClienteLbl = new javax.swing.JLabel();
        nomeClienteTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mesaComboBox = new javax.swing.JComboBox<>();
        obsClienteLbl = new javax.swing.JLabel();
        obsClienteTextField = new javax.swing.JTextField();
        cadastrarMesaBtn = new javax.swing.JButton();
        limparMesaBtn = new javax.swing.JButton();
        cancelarMesaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        produtoComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cliente");

        nomeClienteLbl.setText("Nome:");

        nomeClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Mesa:");

        mesaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaComboBoxActionPerformed(evt);
            }
        });

        obsClienteLbl.setText("Obs:");

        cadastrarMesaBtn.setText("Cadastrar");
        cadastrarMesaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMesaBtnActionPerformed(evt);
            }
        });

        limparMesaBtn.setText("Limpar");
        limparMesaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparMesaBtnActionPerformed(evt);
            }
        });

        cancelarMesaBtn.setText("Cancelar");
        cancelarMesaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarMesaBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        produtoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(nomeClienteLbl)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(obsClienteLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(obsClienteTextField))
                                    .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(produtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cadastrarMesaBtn)
                                .addGap(29, 29, 29)
                                .addComponent(limparMesaBtn)
                                .addGap(27, 27, 27)
                                .addComponent(cancelarMesaBtn)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeClienteLbl)
                    .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obsClienteLbl)
                    .addComponent(obsClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(produtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarMesaBtn)
                    .addComponent(limparMesaBtn)
                    .addComponent(cancelarMesaBtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteTextFieldActionPerformed

    private void cadastrarMesaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMesaBtnActionPerformed
        verificadigitacao();
    }//GEN-LAST:event_cadastrarMesaBtnActionPerformed

    private void limparMesaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparMesaBtnActionPerformed
        limpa();
    }//GEN-LAST:event_limparMesaBtnActionPerformed

    private void cancelarMesaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarMesaBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarMesaBtnActionPerformed

    private void produtoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoComboBoxActionPerformed

    private void mesaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaComboBoxActionPerformed

    
    private void cadastraCliente() {
        Cliente c  = new Cliente();
        ClienteDAO cdao = new ClienteDAO();
        
        Mesa m = (Mesa) mesaComboBox.getSelectedItem();
        Produto p = (Produto) produtoComboBox.getSelectedItem();
        
        c.setNome_cliente(nomeClienteTextField.getText());
        c.setMesa(m);
        c.setObs(obsClienteTextField.getText());
        c.setProduto(p);
        
        
        cdao.save(c);
        limpa();
        
    }
    
    private void limpa() {
        
        nomeClienteTextField.setText(null);
        obsClienteTextField.setText(null);
       
    }
    
    private void verificadigitacao(){
        
        if(nomeClienteTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Favor informar o nome do cliente!");
            obsClienteTextField.requestFocus();
            return;
        }
        if(obsClienteTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Favor informar alguma observação!");
            cadastrarMesaBtn.requestFocus();
            return;
        }
        
         cadastraCliente();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarMesaBtn;
    private javax.swing.JButton cancelarMesaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limparMesaBtn;
    private javax.swing.JComboBox<Object> mesaComboBox;
    private javax.swing.JLabel nomeClienteLbl;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JLabel obsClienteLbl;
    private javax.swing.JTextField obsClienteTextField;
    private javax.swing.JComboBox<Object> produtoComboBox;
    // End of variables declaration//GEN-END:variables
}
